config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations'}
  resources :chat_users
  resources :messages
  resources :chats
  root "activities#index"
  resources :tags
  resources :activities
  resources :users
  get '/logout', to: 'sessions#delete', as: 'logout'
  get '/mylist', to: 'activities#myindex', as: 'mylist'
  get '/myguestlist', to: 'activities#myguestindex', as: 'myguestlist'
  post 'like/:id', to: 'activity_guests#like', as: 'like'
  post 'dislike/:id', to: 'activity_guests#dislike', as: 'dislike'
  post 'approve', to: 'activity_guests#approve'
  post 'deny', to: 'activity_guests#deny'
  post 'remove', to: 'activity_guests#remove'
  post 'read', to: 'chats#read', as: 'read'
  post 'close/:id', to: 'activities#close', as: 'close'
  post 'open/:id', to: 'activities#open', as: 'open'
  get '/activity/:id/additional_info', to: 'activities#modal', as: 'modal'
  post '/giphy', to: "activities#giphy", as: 'giphy'

  resources :chats do
    resources :messages
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :activities, foreign_key: "host_id", dependent: :destroy
  has_many :activity_guests, foreign_key: "guest_id", dependent: :destroy
  has_many :funtimes, through: :activity_guests, source: :activity
  has_many :user_tags, dependent: :destroy
  has_many :tags, through: :user_tags
  has_many :chat_users, dependent: :destroy
  has_many :chats, through: :chat_users, dependent: :destroy

  validates_presence_of :name, :email
  validates_uniqueness_of :email
  validates :uid, uniqueness: true, if: 'uid.present?'

  include UserLikeData
  include UserScoresActivity

  def self.new_from_oauth(auth)
    user = User.new
    user.uid = auth.uid
    user.name = auth.info.name
    user.email = auth.info.email
    user.image_url = auth.info.image + "?type=large"
    user.token = auth.credentials.token
    user.token_expiration = Time.at(auth.credentials.expires_at)
    user.save
    user
  end

  def self.find_or_create_from_oauth(auth)
    if user = self.find_by(uid: auth.uid)
      user.update(token: auth.credentials.token, token_expiration: Time.at(auth.credentials.expires_at))
      user
    else
      self.new_from_oauth(auth)
    end
  end

  def unshown_activities
    activities =  Activity.where.not(host: self).where(aasm_state: "open")
    unshown_activities = activities.map do |activity|
        activity if (!self.funtimes.include?(activity)  && activity.host != self)
    end.compact
    unshown_activities
  end

  def unseen_activity_guests
    current_user_AGs = ActivityGuest.where(guest_id: self.id, aasm_state: "unseen")
    current_user_AGs
  end

  def approved_activities
    current_user_AGs = ActivityGuest.where(guest_id: self.id, aasm_state: "approved")
    current_user_AGs.map {|ag| ag.activity}
  end

  def score_unshown_activities
    unshown_scores = {}
    self.unshown_activities[0..20].each do |activity|
      unshown_scores[activity.id] = self.overall_score(activity)
    end
    unshown_scores
  end

  def fresh_activities
    fresh_activities = self.funtimes.map do |funtime|
      funtime if funtime.activity_guests.where(guest: self)[0].aasm_state == "unseen"
    end.compact
    fresh_activities
  end

  def generate_activity_guests
    unshown_scores = score_unshown_activities
    new_ags = []
    unshown_scores.select{|k, v| unshown_scores.values.max(5).include?(v)}.each do |actid, score|
      new_ags << ActivityGuest.create(guest_id: self.id, activity_id: actid, serv_score: score)
    end
    new_ags
  end

  def show_private_message
    users_to_see = []
    self.activities.each do |activity|
      users_to_see << activity.approved_guests
      users_to_see << activity.interested_guests
    end
    self.activity_guests.each do |ag|
      users_to_see << ag.activity.host if ag.approved?
    end
    users_to_see.flatten.uniq
  end

  def approved_guest_activities_hosted_by host
    activity_guests.eager_load(:activity)
                   .hosted_by(host)
                   .approved
                   .flat_map(&:activity)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    sign_in(:user, User.find(session[:id])) if !current_user
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path
    else
      render "edit"
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    session["warden.user.user.key"][0][0] = nil
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :bio, :image_url, :wants_notifications, :tag_ids => [])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <h2>Edit My Profile:</h2>

  <div class="card activity col-xl-8 col-lg-8 col-md-12 col-sm-12 col-xs-12">
    <div class="person">
      <% if @user.errors %>
        <ul>
          <% @user.errors.full_messages.each do |error| %>
            <li><%=error%></li>
          <% end %>
        </ul>
      <% end %>

      <p>
        <div class="activity-image container" style="background: url(<%= @user.image_url %>) 50% 50% no-repeat;background-size: cover;">
        </div>
      </p>

      <%= form_for(@user, html:{id: 'userForm'}) do |f| %>
        <p>
          <%= f.label :image_url %>:
          <%= f.url_field :image_url %><br />
        </p>

        <p>
          <%= f.label :name%>
          <%= f.text_field :name %><br />
        </p>

        <p>
          <%= f.label :email %>:
          <%= f.email_field :email %><br />
        </p>
        <p>
          <%= f.label :bio %>:
          <p>
            <%= f.text_area :bio, placeholder: "Tell us about yourself!" %><br />
          </p>
        </p>

        <p class="tag-checkboxes">
           <%= f.label :tag_ids, "What kinds of activities are you interested in?" %>
           <%= f.collection_check_boxes(:tag_ids, (Tag.all.sort_by{|tag| tag.name}), :id, :name) do |b|%>
             <div class="row">
               <%= b.label(class: "check_box") do %>
                   <%= b.check_box(class: "check_box") %>
                   <%= b.object.name %>
               <% end %>
             </div>

           <% end %>
         </p>
         <p>
           Would you like email notifications about what's happening on Romp? <br>
           <%= f.label :wants_notifications, "yes!" %>
           <%= f.radio_button(:wants_notifications, true) %>
           <%= f.label :wants_notifications, "no :(" %>
           <%= f.radio_button(:wants_notifications, false) %>
         </p>

        <p>
          <%= f.submit %>
        </p>

      <% end %>
      <%= link_to "Delete your account", user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete your account? This action cannot be undone!"} %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2>My Profile:</h2>

  <div class="card activity col-xl-8 col-lg-8 col-md-8 col-sm-12 col-xs-12 otter">
    <div class="person">
      <h1> <%=@user.name%> </h1>
      <p>
        <div class="activity-image container" style="background: url(<%= @user.image_url %>) 50% 50% no-repeat;background-size: cover;">
        </div>
      </p>
      <% if @user == current_user %>
        <%= link_to edit_user_path do%>
        <button>Update user info</button>
        <% end %>
      <% end %>

      <% if current_user.show_private_message.include? @user %>
        <div class="send-message">
          <h3><%= link_to "Send Private Message", new_chat_path, remote: true %></h3>
        </div>
      <% end %>

      <br>

      <div>
        <% if @user.bio %>
          <%=@user.bio%>
        <% elsif @user == current_user %>
          <%= link_to "Please update your bio", edit_user_path %>
        <% end %>
      </div>
      <hr>
      <div class="tag-list">
       Tags:
       <br>
          <% @user.tags.each do |tag| %>
            <%= "/ " + tag.name + " /" %>
          <% end %>
      </div>
      <hr>

      <div class="approved-list">
        <h5>Approved events:</h5>
          <% ActivityGuest.approved_activity_guests(current_user, @user).each do |x| %>
            <h4><%=link_to x.activity.name, activity_path(x.activity)%></h4>
          <% end %>
      </div>

      <div class="pending-list" id= "<%=@user.id%>">
        <h5>Pending events:</h5>
          <% ActivityGuest.interested_activity_guests(current_user, @user).each do |x| %>
            <div id = "<%=x.id%>">
              <h4><%=x.activity.name%>:</h4>
              <div><%= render partial: 'activities/approval', locals:{activity_guest: x} %></div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
  <% if (@user != current_user)  %>
  <div class="col-md-4 chatz show-page">
  </div>
  <% end %>

</div>