config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations'}
  resources :chat_users
  resources :messages
  resources :chats
  root "activities#index"
  resources :tags
  resources :activities
  resources :users
  get '/logout', to: 'sessions#delete', as: 'logout'
  get '/mylist', to: 'activities#myindex', as: 'mylist'
  get '/myguestlist', to: 'activities#myguestindex', as: 'myguestlist'
  post 'like/:id', to: 'activity_guests#like', as: 'like'
  post 'dislike/:id', to: 'activity_guests#dislike', as: 'dislike'
  post 'approve', to: 'activity_guests#approve'
  post 'deny', to: 'activity_guests#deny'
  post 'remove', to: 'activity_guests#remove'
  post 'read', to: 'chats#read', as: 'read'
  post 'close/:id', to: 'activities#close', as: 'close'
  post 'open/:id', to: 'activities#open', as: 'open'
  get '/activity/:id/additional_info', to: 'activities#modal', as: 'modal'
  post '/giphy', to: "activities#giphy", as: 'giphy'

  resources :chats do
    resources :messages
  end

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :activity
  has_many :chat_users, dependent: :destroy
  has_many :users, through: :chat_users
  has_many :messages, dependent: :destroy

  validates_presence_of :name
  validates :activity_id, uniqueness: true, if: 'activity_id.present?'

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
    chats = current_user.chat_users.map {|cu| cu.chat }
    @chats = chats.sort_by do |chat|
      (chat.messages.last.updated_at if !chat.messages.empty?) || chat.updated_at
    end.reverse!
  end

  def new
    @receiver = User.find(request.env["HTTP_REFERER"].split("/")[4])
    if @chat = current_user.chats.where(personal: true).find {|chat|chat.users.include?(@receiver)}
      @message = Message.new
      respond_to do |format|
        format.js {}
        format.html {redirect_to chat_path(@chat)}
      end
    else
      @chat = Chat.new
      @chat.name = "Private Chat between #{@receiver.name} & #{current_user.name}"
      @chat.personal = true
      @chat.save
      @chat.users << [@receiver, current_user]
      @message = Message.new
      respond_to do |format|
        format.js {}
        format.html {redirect_to chat_path(@chat)}
      end
    end
  end


  def show
    @chat = Chat.find(params[:id])
    @message = Message.new
    cu = ChatUser.find_by(chat: @chat, user: current_user)
    cu.view! if cu.unread?
    respond_to do |format|
      format.js{}
      format.html{}
    end
  end

  def read
    cu = ChatUser.find_by(chat: params[:chat_id], user: current_user)
    cu.view! if cu.unread?
    respond_to do |format|
      format.all { render :nothing => true, :status => 200 }
    end
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chat.html.erb
<div id="chat-<%=chat.id%>" class="chat-zone">
  <div id="messages-<%=chat.id%>" class="chat-box">
    <% chat.messages.each do |message| %>
      <div class="message user-<%= message.sender.id %>">
        <div class="small-text"><strong><%=link_to message.sender.name, user_path(message.sender)%></strong> <%= message.created_at.strftime("%b%e,%l:%M %p") %><br></div>
        <%= message.content %>
      </div>
    <% end %>
  </div>
  <br><br>

  <% if message.errors %>
    <ul>
      <% message.errors.full_messages.each do |error| %>
        <li><%=error%></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for [chat, message], remote: true do |f| %>
  <p>
    <%= f.label :content, "New message" %><br>
    <%= f.text_area :content, placeholder: "Send a new message!" %>
  </p>
    <%= f.submit "Send" %>
  <% end %>
</div>

<script>
  function readMessage() {
    var chatId = <%= chat.id %>
    $('.chat-zone').on('click', function(){
      $.ajax({
        type: "POST",
        url: "<%= read_path %>",
        data: {chat_id: chatId}
      })
    });
  }
  function submitOnEnter() {
    $('#message_content').keydown(function(e){
      if(e.which == 13){
        var chatId = $(this).parents('.chat-zone')[0].id.split("-")[1]
        var messageContent = $(this).val()
        $.ajax({
          method: "POST",
          url: "<%=messages_path%>",
          data: {chat_id: chatId, message: {content: messageContent}}
        })
      }
    })
  }
  readMessage()
  submitOnEnter()
</script>

<%= subscribe_to chat_path(chat) %>

app/views/chats/index.html.erb
<div class="container">

<div class="chat-index col-md-6 otter">
  <h2>My current chats:</h2>

    <% @chats.each do |chat| %>
      <% if chat.personal %>
        <% receiver = chat.users.find{|user| user != current_user} %>
        <div class="outline"> <strong><%= "UNREAD" if chat.chat_users.where(user: current_user)[0].unread? %></strong> <%= link_to "#{receiver.name} (Private Message)", chat_path(chat), remote: true%> </div>
      <% else %>
        <div class="outline"> <strong><%= "UNREAD" if chat.chat_users.where(user: current_user)[0].unread? %></strong> <%= link_to chat.name, chat_path(chat), remote: true %> with <% chat.users.reject do |user| user == current_user end.each do |user| %>
            /<%= (link_to user.name, user_path(user)) %>/
          <% end %>
          <br><strong><%= link_to "Activity Page", activity_path(chat.activity)%></strong>
        </div>
      <% end %>
    <% end %>
</div>
<div class="chat-whole-box col-md-4">

  <div class="chatz show-page">

  </div>
</div>
</div>

app/views/chats/new.js.erb
$('.chatz').html("<%= j render partial: 'chats/chat', locals: {chat: @chat, message: @message} %>")
chat = $('.chatz');
chat.addClass('card')
chat[0].scrollTop = chat[0].scrollHeight;

app/views/chats/show.html.erb
<%= render partial: "chat", locals: {chat: @chat, message: @message} %>

app/views/chats/show.js.erb
$('.chat-whole-box').prepend("<div><h4 class='chat-name'><%=@chat.name%></h4></div>")
$('.chatz').html("<%= j render partial: 'chats/chat', locals: {chat: @chat, message: @message} %>")
chat = $('.chatz');
chat.addClass('card')
chat[0].scrollTop = chat[0].scrollHeight;