config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations'}
  resources :chat_users
  resources :messages
  resources :chats
  root "activities#index"
  resources :tags
  resources :activities
  resources :users
  get '/logout', to: 'sessions#delete', as: 'logout'
  get '/mylist', to: 'activities#myindex', as: 'mylist'
  get '/myguestlist', to: 'activities#myguestindex', as: 'myguestlist'
  post 'like/:id', to: 'activity_guests#like', as: 'like'
  post 'dislike/:id', to: 'activity_guests#dislike', as: 'dislike'
  post 'approve', to: 'activity_guests#approve'
  post 'deny', to: 'activity_guests#deny'
  post 'remove', to: 'activity_guests#remove'
  post 'read', to: 'chats#read', as: 'read'
  post 'close/:id', to: 'activities#close', as: 'close'
  post 'open/:id', to: 'activities#open', as: 'open'
  get '/activity/:id/additional_info', to: 'activities#modal', as: 'modal'
  post '/giphy', to: "activities#giphy", as: 'giphy'

  resources :chats do
    resources :messages
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :host, class_name: "User"
  has_many :activity_tags, dependent: :destroy
  has_many :tags, through: :activity_tags
  has_many :activity_guests, dependent: :destroy
  has_many :guests, through: :activity_guests, class_name: "User"
  has_one :chat, dependent: :destroy

  scope :not_hosted_by, ->(user) { where.not(host: user) }
  scope :hosted_by,     ->(user) { where(host: user) }

  scope :open,   -> { where(aasm_state: 'open') }
  scope :closed, -> { where(aasm_state: 'closed') }

  scope :order_by_most_recent, ->  { order('activities.updated_at DESC') }

  validates_presence_of :host_id, :name, :details, :cost, :guest_min, :guest_max
  validates :guest_max, numericality: {:greater_than_or_equal_to => :guest_min}
  validates :cost, numericality: {greater_than_or_equal_to: 0}
  validates :guest_max, numericality: {greater_than_or_equal_to: 1}
  validates :guest_min, numericality: {greater_than_or_equal_to: 1}
  validate :date_is_in_the_future

  include AASM

  aasm do
    state :open, :initial => true
    state :closed
    state :deleted

    event :close do
      transitions :from => :open, :to => :closed
    end

    event :reopen do
      transitions :from => :closed, :to => :open
    end

    event :soft_delete do
      transitions :from => [:open, :closed], :to => :deleted
    end

  end

  def date_is_in_the_future
    if datetime.present? && datetime < Date.today
      errors.add(:datetime, "stop living in the past.")
    end
  end

  def interested_guests
    activity_guests.liked.flat_map(&:guest)
  end

  def approved_guests
    activity_guests.approved.flat_map(&:guest)
  end

end

app/controllers/activities_controller.rb
require 'net/http'
class ActivitiesController < ApplicationController

  def index
    if user_signed_in?
      if current_user.unseen_activity_guests.length < 5
        current_user.generate_activity_guests
      end
      @fresh_activities = current_user.fresh_activities
    end
  end

  def myindex
    if user_signed_in?
      @open_activities   = current_user.activities.open.order_by_most_recent
      @closed_activities = current_user.activities.closed.order_by_most_recent
    else
      redirect_to root_path #EVENTUALLY THIS WILL NEED TO BE JS TO SUGGEST LOGGING IN
    end
  end

  def myguestindex
    @approved_activities = current_user.approved_activities.order_by_most_recent
  end

  def giphy
    search_term = params[:search_term].gsub(" ", "+")
    url = "http://api.giphy.com/v1/gifs/search?q=" + search_term + "&api_key=dc6zaTOxFJmzC&limit=5"
    resp = Net::HTTP.get_response(URI.parse(url))
    buffer = resp.body
    result = JSON.parse(buffer)
    @urls = result["data"].map {|result| result["images"]["fixed_height"]["url"]}
    respond_to do |format|
      format.js {}
      format.html {redirect_to mylist_path}
    end
  end

  def new
    if user_signed_in?
      @activity = Activity.new
      respond_to do |format|
        format.js{}
        format.html{}
      end
    else
      redirect_to root_path #EVENTUALLY THIS WILL NEED TO BE JS TO SUGGEST LOGGING IN
    end
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.host = current_user
    if @activity.save
        respond_to do |format|
          format.js {}
          format.html {redirect_to mylist_path}
        end
    else
      render "new"
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @chat = @activity.chat || Chat.create(name: @activity.name, activity: @activity)
    @message = Message.new
  end

  def edit
    @activity = Activity.find(params[:id])
    respond_to do |format|
      format.js{}
      format.html{}
    end
  end

  def update
    @activity = Activity.find(params[:id])
    source = request.env["HTTP_REFERER"].split("/")[3]
    if @activity.update(activity_params)
      if source == "mylist"
        respond_to do |format|
        format.js {}
        format.html {redirect_to activity_path(@activity)}
        end
      else
        respond_to do |format|
        format.js {render "other_update"}
        format.html {redirect_to activity_path(@activity)}
        end
      end
    else
      render "edit"
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    if current_user.id != @activity.host_id
      redirect_to mylist_path
    else
      @activity.soft_delete!
      redirect_to mylist_path
    end
  end

  def close
    @activity = Activity.find(params[:id])
    @activity.close!
    respond_to do |format|
      format.js {}
      format.html {redirect_to mylist_path}
    end
  end

  def open
    @activity = Activity.find(params[:id])
    @activity.reopen!
    respond_to do |format|
      format.js {}
      format.html {redirect_to mylist_path}
    end
  end

  def modal
    @activity = Activity.find(params[:id])
    respond_to do |format|
      format.js {}
      format.html {redirect_to activity_path(@activity)}
    end
  end

  private
  def activity_params
    params.require("activity").permit(:name, :guest_min, :guest_max, :details, :cost, :image_url, :host_id, :tag_ids => [])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_interested_guests.html.erb
<div class="interested-guests" id="<%=activity.id%>">
  Interested Guests:
  <ul>
    <% activity.activity_guests.where(aasm_state: "liked").each do |ag| %>
        <li><%=link_to user_path(ag.guest), id: "#{ag.guest.id}" do %>
          <div class="">
            <%= image_tag(ag.guest.image_url, class: "col-md-3 col-xs-3") %>
            <%= ag.guest.name %>
          </div>
          <% end %>
          <div>
            <%= render partial: 'approval', locals:{activity_guest: ag} %>
          </div>
        </li>
    <% end %>
  </ul>
</div>

app/views/activities/_modal.html.erb
<div class="my-modal modal fade" id="newActivityModal" tabindex="-1" role="dialog" aria-labelledby="newActivityLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2>what do you want to do?</h2>
      </div>
      <div class="modal-body modal-footer">
        <% @activity = Activity.new %>
      <%= render "activities/form" %>
      </div>
    </div>
  </div>
</div>

app/views/activities/create.js.erb
$('#newActivityModal').modal('hide')
$('.open-activities').prepend("<%= j render partial: 'activity', locals: {activity: @activity} %>")

window.location = "<%= mylist_path %>"

app/views/activities/edit.html.erb
<div class="container">
  <div class="card col-xl-6 col-lg-6 col-md-8 col-sm-12 col-xs-12">

  <div class="activity-image" style="background: url(<%= @activity.image_url %>) 50% 50% no-repeat;background-size: cover;">
  </div>

    <%= render 'form' %>

  </div>
</div>

app/views/activities/giphy.js.erb
var form = "<%= j render partial: 'activities/giphy' %>";
$("#giphy_result").replaceWith(form);
setTimeout(function(){
  linkGiphys();
}, 500);

app/views/activities/index.html.erb
<% if user_signed_in? %>

<div class="container">
  <% if @fresh_activities && !@fresh_activities.empty? %>
    <div id="tinderslide" class="stack stack-randomrot active">
      <ul>
        <%= render @fresh_activities  %>
      </ul>
    </div>
  <% end %>

</div>

<div class="my-modal modal fade" id="showActivityModal" tabindex="-1" role="dialog" aria-labelledby="showActivityLabel">
  <div class="modal-dialog" role="document">

      <div class="show-activity">

      </div>
    </div>
  </div>
</div>


<script>
  var activityModal = function(){
    $('.stack-randomrot').on('click', ".name-click", function(e){
      e.preventDefault()
      var activityId = this.href.split('/')[4]

      $.ajax({
        type: "GET",
        url: "/activity/" + activityId + "/additional_info",
      });
    });
  }
  activityModal()
</script>

<% else %>

<div class="container">
  <div class="fun-facts parallax testi">

    <div class="col-md-3 margin-btm-20">
      <div class="fact-inner">
        <h1 class="super-large">welcome to </h1><h1 class="super-super-large">romp</h1>
      </div>
    </div>
    <div class="col-md-3 margin-btm-20">
      <div class="fact-inner">
        <h3>meet people in nyc who like the same stuff you do. then get out and do the damn thing!</h3>
      </div>
    </div>
    <div class="col-md-3 margin-btm-20">
      <div class="fact-inner">
        <h5 class="be-normal">share an adventure you've always wanted to go on, a favorite pastime you're too embarrassed to tell your friends about, or an event it'd be nice to have a little company for.</h5>
      </div>
    </div>
    <div class="col-md-3 margin-btm-20">
      <div class="fact-inner">
        <h3 class="super-large">sign up now to start romping!</h3>
      </div>
    </div>

    <%= image_tag("otter_large_flipped.png", class: "fact-inner col-md-3 margin-btm-20", id: "otter-pic") %>

  </div>



</div>

<% end %>

app/views/activities/modal.js.erb
$('#showActivityModal').modal()
$('.show-activity').html("<%= j render partial: 'activities/activity_modal', locals: {activity: @activity} %>")

app/views/activities/myindex.html.erb
<div class="container">

  <h2>Open Activities</h2>
  <ul class="open-activities container center-container">
    <% if !@open_activities.empty? %>
      <div class="row">
        <%= render @open_activities %>
      </div>
    <% end %>
    </ul>

  <br><br>
    <h2>Closed Activities</h2>
    <ul class="closed-activities">
      <% if !@closed_activities.empty? %>
        <%= render @closed_activities %>
      <% end %>
    </ul>
</div>

<div class="my-modal modal fade" id="editActivityModal" tabindex="-1" role="dialog" aria-labelledby="showActivityLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container otter clearfix">
  <%= render 'form' %>
</div>

app/views/activities/new.js.erb
var new_form = "<%= j render partial: 'form', locals: {activity: @activity} %>"
$("#newActivityModal .modal-body").html(new_form)
var activityValidator = new FormValidations();
  setTimeout(function(){
    activityValidator.activityForm();
}, 500);

app/views/activities/open.js.erb
var actid = <%=@activity.id%>
var form = "<%= j render @activity %>"
$("#" + actid).remove()
$(".open-activities").append(form)

app/views/activities/other_update.js.erb
$('#editActivityModal').modal('hide')
$(".show-page-card").html("<%= j render partial: 'activities/show_page_card', locals: {activity: @activity} %>");

app/views/activities/show.html.erb
<div class="container ferret">
  <div class="show-page-card">
    <%= render partial: "activities/show_page_card", locals: {activity: @activity} %>
  </div>
  <% if (@activity.host == current_user) || (@activity.approved_guests.include? current_user) %>
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 chatz show-page card show-chat">
      <%= render partial: "chats/chat", locals: {chat: @chat, message: @message} %>
    </div>

    <script>
      var chatScrollListener = function(){
        chat = $('.chatz');
        chat[0].scrollTop = chat[0].scrollHeight;
      };
      chatScrollListener();
    </script>
  <% end %>

  <% if user_signed_in? && current_user.id == @activity.host_id %>
    <div class="activity card col-md-3 col-lg-4 col-xs-12 col-sm-12">
      <div class="">
        <%= link_to "edit this", edit_activity_path(@activity), "data-toggle": "modal", "data-target": "#editActivityModal", remote: true    %>
      </div>
      <% if @activity.open? %>
        <div class="">
          <%= link_to "close this", close_path(@activity), method: :post, remote: true %>
        </div>
      <% elsif @activity.closed? %>
        <div class="">
          <%= link_to "open this", open_path(@activity), method: :post, remote: true  %>
        </div>
      <% end %>
      <div class="">
        <%= link_to "delete this", activity_path(@activity), method: :delete, data: {confirm: "Are you sure you want to delete this activity? This action cannot be undone!"} %>
      </div>
  </div>
  <% end %>
</div>

<div class="my-modal modal fade" id="editActivityModal" tabindex="-1" role="dialog" aria-labelledby="showActivityLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>

app/views/activities/update.js.erb
$('#editActivityModal').modal('hide')
$("li#<%=@activity.id%>").replaceWith("<%=j render partial: 'activities/activity', locals: {activity: @activity}%>");