config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations'}
  resources :chat_users
  resources :messages
  resources :chats
  root "activities#index"
  resources :tags
  resources :activities
  resources :users
  get '/logout', to: 'sessions#delete', as: 'logout'
  get '/mylist', to: 'activities#myindex', as: 'mylist'
  get '/myguestlist', to: 'activities#myguestindex', as: 'myguestlist'
  post 'like/:id', to: 'activity_guests#like', as: 'like'
  post 'dislike/:id', to: 'activity_guests#dislike', as: 'dislike'
  post 'approve', to: 'activity_guests#approve'
  post 'deny', to: 'activity_guests#deny'
  post 'remove', to: 'activity_guests#remove'
  post 'read', to: 'chats#read', as: 'read'
  post 'close/:id', to: 'activities#close', as: 'close'
  post 'open/:id', to: 'activities#open', as: 'open'
  get '/activity/:id/additional_info', to: 'activities#modal', as: 'modal'
  post '/giphy', to: "activities#giphy", as: 'giphy'

  resources :chats do
    resources :messages
  end

end

app/views/layouts/_footer.html.erb
<section id="footer" class="padding-80">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 copyright">
                <span>&copy;2016. Precognitioned, LLC. All rights reserved.</span>
            </div>
            <div class="col-md-6 col-sm-6 footer-nav">
              <span>
                  Made with <span class="glyphicon glyphicon-heart"></span> by
                  <%= link_to "@eaud", "https://github.com/eaud/" %>,
                  <%= link_to "@jappleba", "https://github.com/jappleba/" %>,
                  & <%= link_to "@kaylee42", "https://github.com/kaylee42/" %>.
                </span>
            </div>
        </div>
    </div>
</section><!--footer end-->

app/views/layouts/_header.html.erb
<!-- CODEON VERSION OF HEADER -->

<section id="navigation" class="fixed-navigation">
    <div class="navbar navbar-default navbar-static-top navbar-transparent" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "romp", root_path, class:"navbar-brand" %>
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav navbar-right scrollto">
                    <% if user_signed_in? %>
                      <li class="active"><%= link_to "My Hosted Events", mylist_path %></li>
                      <li class="active"><%= link_to "My Guest Events", myguestlist_path %></li>
                      <li><%= link_to "Add an Activity", new_activity_path, "data-toggle": "modal", "data-target": "#newActivityModal", remote: true %></li>
                      <li><%= link_to "Chat Center", chats_path %></li>
                      <li class="dropdown">
                          <a href="#" data-toggle="dropdown" class="dropdown-toggle js-activated">My Account <b class="caret"></b></a>
                          <ul class="dropdown-menu">
                            <li><%=link_to "View Profile", current_user%></li>
                            <li><%=link_to "Edit Profile", edit_user_path(current_user)%></li>
                            <li><%=link_to "Logout", logout_path%></li>
                            <li role="separator" class="divider"></li>
                          </ul>
                      </li>
                    <% else %>
                      <li class="dropdown">
                            <li><%= (link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)) %></li>
                            <li><%= (link_to "Signup with email", new_user_registration_path, id: "sign_up_email") %></li>
                      </li>
                    <% end %>

                </ul>

            </div><!--/.nav-collapse -->
        </div><!--/.container -->
    </div>
</section><!--navigation section end here-->

<div class="my-modal modal fade" id="newActivityModal" tabindex="-1" role="dialog" aria-labelledby="newActivityLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2>what do you want to do?</h2>
      </div>
      <div class="modal-body modal-footer">

      </div>
    </div>
  </div>
</div>

app/views/layouts/_not_logged_in.html.erb
"LOG YOUR ASS IN"

app/views/layouts/application.html.erb
<html lang="en">
    <head>
        <title>romp</title>
        <style media="screen">
        .user-<%=current_user.id if user_signed_in?%> {text-align:right;}
        </style>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0,target-densitydpi=device-dpi, user-scalable=no" />
        <!--custom css-->
        <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--google web fonts css-->
        <link href='https://fonts.googleapis.com/css?family=Raleway:400,300,500,600,800' rel='stylesheet' type='text/css'>
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <script src="js/respond.min.js"></script>
        <![endif]-->
    </head>
      <%= render "layouts/header" %>
      <body data-spy="scroll" data-target="#navigation" data-offset="80">

      <div id="wrap" class= "clearfix">

        <div >
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>

          <%= yield %>

      </div>

          <%= render "layouts/footer" %>

      </body>
</html>